apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: q4alp9f4j-go 
  janus-idp.io/tekton: q4alp9f4j-go
  backstage.io/kubernetes-id: q4alp9f4j-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: q4alp9f4j-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml